nome = input('Qual o seu nome? ')
idade = int(input('Qual sua idade? '))
peso = int(input('Qual o seu peso? '))

print(nome, idade, peso)
print('Prazer, {}, você tem {} com o peso de {}'.format(nome, idade, peso))
print('Prazer {}!'.format(nome))
print('Prazer {:20}!'.format(nome))
print('Prazer {:<20}!'.format(nome))
print('Prazer {:>20}!'.format(nome))
print('Prazer {:^20}!'.format(nome))
print('Prazer {:=^20}!'.format(nome))
print( 'A soma de peso + idade foi: {}'.format(idade + peso))
print('Não quebrar essa linha {}'.format(nome), end=' ')
print('com essa linha'.format(idade))
print('Quebrar essa linha {} \n com essa linha {}'.format(nome, idade))
